# Generated by Django 4.0.4 on 2022-04-28 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tipousuario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nombreP',
        ),
        migrations.CreateModel(
            name='HistorialCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreH', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=30)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=30)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
        ),
    ]
